"use client";
import {useEffect,useRef} from "react";
import type {Transaction} from "./transactions";
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
export function useLedgerTools(rows:Transaction[],demo:boolean,navigate:(view:string)=>void){
 const latest=useRef({rows,demo,navigate});latest.current={rows,demo,navigate};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();
 const tool:Tool={name:"read_ledger_transactions",title:"Read Ledger transactions",description:"Read up to 100 transactions currently available in Ledger, with optional account and merchant filters. Does not import or change data.",inputSchema:{type:"object",properties:{account:{type:"string",enum:["all","amex","discover"]},search:{type:"string",maxLength:200}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=="object"||Array.isArray(input))throw Error("Expected an object.");const value=input as Record<string,unknown>;if(Object.keys(value).some(k=>!["account","search"].includes(k)))throw Error("Unknown filter.");const account=value.account??"all",search=value.search??"";if(!["all","amex","discover"].includes(account as string)||typeof search!=="string"||search.length>200)throw Error("Invalid filters.");const result=latest.current.rows.filter(t=>(account==="all"||t.source===account)&&t.merchant.toLowerCase().includes(search.toLowerCase()));return {sampleData:latest.current.demo,amountUnit:"USD cents",total:result.length,transactions:result.slice(0,100)};}};
 try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{/* Browsers without WebMCP still support every visible flow. */}return()=>controller.abort();},[]);
}
