"use client";
import {useState,useEffect,useMemo,useRef} from "react";
import {ArrowDownLeft,ArrowRight,ArrowUpRight,CreditCard,LayoutDashboard,ListFilter,Plus,Repeat2,Sparkles,Wallet,Upload,ChevronRight,Link2,Loader2} from "lucide-react";
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from "@/components/ui/sidebar";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {money,monthKey,spendingBreakdown,categoryTotals,accountOptions,filterAccountTransactions,importedAccounts,type Source,type AccountView,type Transaction,type LinkedAccount,type PlaidStatus} from "@/lib/transactions";
import {TransactionTable} from "./transaction-table";
import {TransactionsView,RecurringView,InsightsView,ImportDialog} from "./budget-views";
import {Toaster} from "@/components/ui/sonner";
import {Skeleton} from "@/components/ui/skeleton";
import {toast} from "sonner";
import {useLedgerTools} from "@/lib/webmcp";
import {ConnectedAccounts,PlaidSetup} from "./connected-accounts";
import {api,startPlaid} from "@/lib/plaid-link";
const nav=[{name:"Overview",icon:LayoutDashboard},{name:"Transactions",icon:ListFilter},{name:"Recurring",icon:Repeat2},{name:"AI insights",icon:Sparkles},{name:"Accounts",icon:CreditCard}];
const colors=["#248a86","#8283db","#609bc5","#e7b467","#d086a7","#8d9aab"];
export default function BudgetApp() {
 const [view,setView]=useState("Overview"),[account,setAccount]=useState("all");
 const [rows,setRows]=useState<Transaction[]>([]),[month,setMonth]=useState("current"),[provider,setProvider]=useState<AccountView>("cards");
 const [accounts,setAccounts]=useState<LinkedAccount[]>([]),[plaid,setPlaid]=useState<PlaidStatus>({ready:false,missing:[],message:"Checking connection setup…"});
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[aiConfigured,setAiConfigured]=useState(false),[importOpen,setImportOpen]=useState(false),[setupOpen,setSetupOpen]=useState(false),[busy,setBusy]=useState(false);
 const syncLock=useRef(false),retryTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 async function load(){setError("");try{const data=await api<{transactions:Transaction[];aiConfigured:boolean;accounts:LinkedAccount[];plaid:PlaidStatus}>("/api/transactions");setRows(data.transactions);setAccounts(data.accounts);setPlaid(data.plaid);setAiConfigured(data.aiConfigured);return data;}catch(e){setError(e instanceof Error?e.message:"Unable to load transactions.");return null;}finally{setLoading(false);}}
 async function sync(itemId?:string,quiet=false,attempt=0){if(syncLock.current)return;syncLock.current=true;setBusy(true);try{const data=await api<{results:{ok:boolean;error?:string;waitingForHistory?:boolean;skippedCurrency?:number}[]}>("/api/plaid/sync",{itemId});const failures=data.results.filter(r=>!r.ok);await load();if(failures.length)setError(failures.map(r=>r.error).join(" "));else if(!quiet)toast.success("Cards synced with the latest data available from Plaid.");if(data.results.some(r=>r.skippedCurrency))toast.info("Non-USD transactions were excluded from this USD workspace.");if(attempt<4&&data.results.some(r=>r.waitingForHistory)){retryTimer.current=setTimeout(()=>void sync(itemId,true,attempt+1),[5000,10000,20000,40000][attempt]);}}catch(e){setError(e instanceof Error?e.message:"Sync failed.");}finally{syncLock.current=false;setBusy(false);}}
 async function connect(itemId?:string){if(busy)return;if(!plaid.ready){setSetupOpen(true);return;}setBusy(true);setError("");try{await startPlaid({itemId,onSaved:async id=>{setProvider("cards");setView("Accounts");await sync(id);},onExit:()=>setBusy(false),onError:message=>{setError(message);setBusy(false);}});}catch(e){setError(e instanceof Error?e.message:"Could not open Plaid.");setBusy(false);}}
 async function disconnect(itemId:string){setBusy(true);try{await api("/api/plaid/disconnect",{itemId});await load();toast.success("Disconnected. Your transaction history has been kept.");}catch(e){setError(e instanceof Error?e.message:"Could not disconnect.");}finally{setBusy(false);}}
 useEffect(()=>{let active=true;void load().then(data=>{if(!active||!data)return;if(!data.accounts.length&&!data.transactions.some(t=>t.provider==="plaid"||t.source==="apple")&&data.transactions.some(t=>t.provider==="csv"))setProvider("csv");if(data.plaid.ready&&data.accounts.some(a=>!a.lastSynced||Date.now()-Date.parse(a.lastSynced)>300000||new URLSearchParams(window.location.search).has("connected")))void sync(undefined,true);});const timer=setInterval(()=>{if(document.visibilityState==="visible")void load().then(data=>{if(active&&data?.plaid.ready&&data.accounts.length)void sync(undefined,true);});},300000);return()=>{active=false;clearInterval(timer);if(retryTimer.current)clearTimeout(retryTimer.current);};},[]);
 const currentMonth=monthKey(),selectedMonth=month==="current"?currentMonth:month;
 const providerRows=filterAccountTransactions(rows,provider,"all"),importedCards=importedAccounts(rows);
 const months=useMemo(()=>[...new Set(providerRows.map(t=>t.date.slice(0,7)))].sort().reverse(),[rows,provider]);
 const options=accountOptions(accounts,rows,provider);
 const selectedAccount=options.some(option=>option.value===account)?account:"all";
 const accountLabel=options.find(option=>option.value===selectedAccount)?.label||"All accounts";
 useEffect(()=>{if(account!=="all"&&!options.some(option=>option.value===account))setAccount("all");},[account,accounts,rows,provider]);
 const accountRows=filterAccountTransactions(rows,provider,selectedAccount);
 const openImport=()=>setImportOpen(true);
 const imported=(transactions:Transaction[],added:number,duplicates:number,source:Source)=>{setRows(transactions);setProvider(source==="apple"?"cards":"csv");setAccount(`csv:${source}`);setMonth("current");setView("Overview");setImportOpen(false);setError("");toast.success(`${added} transactions imported${duplicates?` · ${duplicates} duplicates skipped`:""}`);};
 const showImportedCard=(id:string)=>{setProvider(id==="csv:apple"?"cards":"csv");setAccount(id);setView("Transactions");};
 useLedgerTools(providerRows);
 const current=accountRows.filter(t=>selectedMonth==="all"||t.date.startsWith(selectedMonth));
 const breakdown=spendingBreakdown(current),total=breakdown.net,categories=categoryTotals(current,"purchases");
 return <SidebarProvider style={{"--sidebar-width":"238px"} as React.CSSProperties}>
 <Sidebar className="ledger-sidebar"><SidebarHeader className="ledger-sidebar-header"><a className="brand" href="/"><span className="brand-mark"><Wallet size={23}/></span>ledger<span className="brand-period">.</span></a></SidebarHeader><SidebarContent className="ledger-sidebar-scroll" tabIndex={0} aria-label="Sidebar navigation"><div className="workspace-label">YOUR WORKSPACE</div><SidebarMenu>{nav.map(({name,icon:Icon})=><SidebarMenuItem key={name}><SidebarMenuButton className="nav-button" isActive={view===name} onClick={()=>setView(name)}><Icon size={19}/><span>{name}</span>{name==="AI insights"&&<span className="ai-tag">AI</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-accounts"><div className="workspace-label">YOUR ACCOUNTS</div>{accounts.length?accounts.map(a=><div key={a.id}><span className={`mini-card ${a.source}`}>{a.source==="amex"?"A":a.source==="discover"?"D":"C"}</span><span>{a.institution}{a.mask?` · ${a.mask}`:""}</span></div>):!importedCards.length&&<div>No cards added</div>}{importedCards.map(a=><button key={a.id} className="imported-sidebar-card" onClick={()=>showImportedCard(a.id)}><span className={`mini-card ${a.source}`}><CreditCard size={15}/></span><span>{a.name}<small>CSV import</small></span></button>)}<button onClick={()=>void connect()}><Plus size={16}/>Add an account</button></div></SidebarContent><SidebarFooter className="ledger-sidebar-footer"><div className="profile"><span>V</span><div><strong>Personal workspace</strong><small>Your financial picture</small></div></div></SidebarFooter></Sidebar>
 <div className="app-shell"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger className="mobile-trigger"/><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="topbar-right"><span className="data-pill">Your real transactions</span><span className="avatar">V</span></div></header>
 <main className="page"><div className="page-title"><div><div className="eyebrow">THE BIG PICTURE</div><h1>{view==="Overview"?"Your spending, at a glance":view}</h1><p>{view==="Recurring"?"The payments that come around again. All available history.":view==="AI insights"?"A conversation with your financial picture.":view==="Accounts"?"Your actual cards, connected in one place.":"All your cards. A clearer view of where your money goes."}</p></div><div className="page-actions"><button className="outline-button compact-button" onClick={openImport}><Upload size={16}/>Import CSV</button><button className="primary-button" disabled={busy||loading} onClick={()=>void connect()}>{busy?<Loader2 className="animate-spin" size={16}/>:<Link2 size={16}/>}Connect a card</button></div></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={load}>Retry</button></div>}
 {loading&&<div className="loading-line" role="status"><Skeleton className="h-3 w-36"/>Loading your transactions…</div>}
 {view!=="Accounts"&&<><div className="data-source-switch"><button aria-pressed={provider==="cards"} onClick={()=>{setProvider("cards");}}>My cards</button><button aria-pressed={provider==="csv"} onClick={()=>{setProvider("csv");}}>CSV statements</button></div><div className="filter-row">{view==="Recurring"?<span className="history-scope">All available history</span>:<Select value={month} onValueChange={setMonth}><SelectTrigger aria-label="Select period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="current">Current month</SelectItem><SelectItem value="all">All time</SelectItem>{months.filter(m=>m!==currentMonth).map(m=><SelectItem key={m} value={m}>{new Date(m+"-01T12:00:00Z").toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</SelectItem>)}</SelectContent></Select>}<Select value={selectedAccount} onValueChange={setAccount}><SelectTrigger aria-label="Filter accounts" className="account-filter" title={accountLabel}><CreditCard size={15}/><SelectValue/></SelectTrigger><SelectContent className="account-filter-options" position="popper" align="end"><SelectItem value="all">All accounts</SelectItem>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div></>}
 {view==="Overview"&&!loading&&!providerRows.length&&<div className="empty-state panel real-empty"><CreditCard size={38}/><h2>{provider==="cards"?(accounts.length?"Your cards are connected":"Start with your first card"):"No statements imported yet"}</h2><p>{provider==="cards"?(accounts.length?"Your institution is preparing transaction history. Use Sync on the Accounts page to check for updates.":"Connect Amex or Discover to see your actual spending, recurring payments, and insights."):"Import an Apple Card, Amex, or Discover CSV to see your real transactions."}</p><button className="primary-button" disabled={busy} onClick={()=>provider==="cards"?(accounts.length?setView("Accounts"):void connect()):openImport()}>{provider==="cards"?(accounts.length?"View connected accounts":"Connect a card"):"Import a statement"}</button></div>}
 {view==="Overview"&&providerRows.length>0&&<><section className="stats-grid"><div className="stat-card"><div className="stat-label">Net spent <span><ArrowUpRight size={17}/></span></div><div className="stat-number">{money(total)}</div><div className="stat-foot">Posted purchases minus refunds and credits · pending and card payments excluded</div></div><div className="stat-card"><div className="stat-label">Transactions <span><ArrowDownLeft size={17}/></span></div><div className="stat-number">{current.length}<span className="stat-unit">in this period</span></div><div className="stat-foot">Across {new Set(current.map(t=>t.accountId||t.source)).size} accounts</div></div><div className="stat-card"><div className="stat-label">Top category <span><Wallet size={17}/></span></div><div className="stat-number smaller">{categories[0]?.name||"—"}</div><div className="stat-foot"><strong>{money(categories[0]?.value||0)}</strong> in posted purchases</div></div></section>
 <div className="overview-grid"><section className="panel spending-panel"><div className="panel-heading"><div><h2>Where it’s going</h2><p>Posted purchases by category</p></div><span className="subtle-label">SELECTED PERIOD</span></div><div className="category-layout"><div className="donut" style={{background:categories.length?`conic-gradient(${categories.map((c,i)=>`${colors[i%colors.length]} ${categories.slice(0,i).reduce((s,x)=>s+x.value,0)/categories.reduce((s,x)=>s+x.value,0)*100}% ${categories.slice(0,i+1).reduce((s,x)=>s+x.value,0)/categories.reduce((s,x)=>s+x.value,0)*100}%`).join(",")})`:"#e9eef1"}}><div><small>Purchases</small><strong>{money(breakdown.purchases)}</strong><span>{categories.length} categories</span></div></div><div className="category-legend">{categories.map((c,i)=><div key={c.name}><i style={{background:colors[i%colors.length]}}/><span>{c.name}</span><strong>{money(c.value)}</strong></div>)}</div></div><div className="spending-reconciliation" aria-label="Spending calculation"><div><span>Posted purchases</span><strong>{money(breakdown.purchases)}</strong></div><div><span>Refunds &amp; credits</span><strong>−{money(breakdown.credits)}</strong></div><div className="reconciliation-net"><span>Net spent</span><strong>{money(total)}</strong></div><div className="reconciliation-excluded"><span>Pending purchases · excluded</span><strong>{money(breakdown.pendingPurchases)}</strong></div><div className="reconciliation-excluded"><span>Card payments · excluded</span><strong>{money(breakdown.payments)}</strong></div></div></section><section className="insight-teaser"><span className="insight-symbol"><Sparkles size={23}/></span><div className="eyebrow">A FRESH PERSPECTIVE</div><h2>Meet your money.<br/>Make sense of it.</h2><p>Ask about your spending, spot patterns, and understand what comes around every month.</p><button onClick={()=>setView("AI insights")}>Ask Ledger <ArrowUpRight size={17}/></button><span className="insight-caption">Insights grounded in your transactions</span></section></div>
 <section className="panel transactions-panel"><div className="panel-heading"><div><h2>Recent transactions <span className="count-label">{current.length}</span></h2><p>A little bit of your everyday, all in one place.</p></div><button className="text-button" onClick={()=>setView("Transactions")}>View all transactions <ArrowRight size={16}/></button></div><TransactionTable rows={current.slice(0,6)}/></section>
 </>}
 {view==="Transactions"&&<TransactionsView rows={current} onImport={openImport}/>}
 {view==="Recurring"&&<RecurringView rows={accountRows} onImport={openImport}/>}
 {view==="Accounts"&&<ConnectedAccounts accounts={accounts} importedCards={importedCards} onViewImported={showImportedCard} status={plaid} busy={busy} connect={connect} sync={sync} disconnect={disconnect} onImport={openImport}/>}
 {view==="AI insights"&&<InsightsView aiConfigured={aiConfigured} month={selectedMonth} account={selectedAccount} accountLabel={accountLabel} provider={provider}/>}
 <PlaidSetup open={setupOpen} onOpenChange={setSetupOpen} status={plaid}/><ImportDialog open={importOpen} onOpenChange={setImportOpen} onImported={imported}/><Toaster position="bottom-right"/>
 <footer className="page-footer"><span>Made for a little more peace of mind.</span><span>USD · Your connected cards and imported statements</span></footer></main></div></SidebarProvider>;
}
