"use client";
import {useState,useEffect,useMemo} from "react";
import {ArrowDownLeft,ArrowRight,ArrowUpRight,CreditCard,LayoutDashboard,ListFilter,Plus,Repeat2,Sparkles,Wallet,Upload,ChevronRight} from "lucide-react";
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from "@/components/ui/sidebar";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {demoTransactions,money,spending,categoryTotals,shortDate,type Transaction} from "@/lib/transactions";
import {TransactionTable} from "./transaction-table";
import {TransactionsView,RecurringView,AccountsView,InsightsView,ImportDialog} from "./budget-views";
import {Toaster} from "@/components/ui/sonner";
import {Skeleton} from "@/components/ui/skeleton";
import {toast} from "sonner";
import {useLedgerTools} from "@/lib/webmcp";
const nav=[{name:"Overview",icon:LayoutDashboard},{name:"Transactions",icon:ListFilter},{name:"Recurring",icon:Repeat2},{name:"AI insights",icon:Sparkles},{name:"Accounts",icon:CreditCard}];
const colors=["#248a86","#8283db","#609bc5","#e7b467","#d086a7","#8d9aab"];
export default function BudgetApp() {
 const [view,setView]=useState("Overview"),[source,setSource]=useState("all");
 const [rows,setRows]=useState<Transaction[]>(()=>demoTransactions()),[month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [demo,setDemo]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(""),[aiConfigured,setAiConfigured]=useState(false),[importOpen,setImportOpen]=useState(false);
 async function load(){setLoading(true);setError("");try{const res=await fetch("/api/transactions");const data=await res.json() as {error?:string;aiConfigured:boolean;transactions:Transaction[]};if(!res.ok)throw Error(data.error);setAiConfigured(data.aiConfigured);if(data.transactions.length){setRows(data.transactions);setDemo(false);setMonth(data.transactions[0].date.slice(0,7));}}catch(e){setError(e instanceof Error?e.message:"Unable to load transactions.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const months=useMemo(()=>[...new Set(rows.map(t=>t.date.slice(0,7)))].sort().reverse(),[rows]);
 const accountRows=rows.filter(t=>source==="all"||t.source===source);
 const openImport=()=>setImportOpen(true);
 const imported=(transactions:Transaction[],added:number,duplicates:number)=>{setRows(transactions);setDemo(false);setMonth(transactions[0]?.date.slice(0,7)||month);setImportOpen(false);setError("");toast.success(`${added} transactions imported${duplicates?` · ${duplicates} duplicates skipped`:""}`);};
 useLedgerTools(rows,demo,setView);

 const current=rows.filter(t=>(month==="all"||t.date.startsWith(month))&&(source==="all"||t.source===source));
 const total=spending(current),categories=categoryTotals(current);
 return <SidebarProvider style={{"--sidebar-width":"238px"} as React.CSSProperties}>
 <Sidebar className="ledger-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-mark"><Wallet size={23}/></span>ledger<span className="brand-period">.</span></a></SidebarHeader><SidebarContent><div className="workspace-label">YOUR WORKSPACE</div><SidebarMenu>{nav.map(({name,icon:Icon})=><SidebarMenuItem key={name}><SidebarMenuButton className="nav-button" isActive={view===name} onClick={()=>setView(name)}><Icon size={19}/><span>{name}</span>{name==="AI insights"&&<span className="ai-tag">AI</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-accounts"><div className="workspace-label">YOUR ACCOUNTS</div><div><span className="mini-card amex">A</span>American Express</div><div><span className="mini-card discover">D</span>Discover</div><button onClick={()=>setView("Accounts")}><Plus size={16}/>Add an account</button></div></SidebarContent><SidebarFooter><div className="sidebar-note"><span className="tiny-orbit"><Sparkles size={16}/></span><strong>A little more clarity.</strong><p>Let your transactions tell the bigger story.</p><button onClick={()=>setView("AI insights")}>Explore your insights <ArrowRight size={15}/></button></div><div className="profile"><span>V</span><div><strong>Personal workspace</strong><small>Your financial picture</small></div></div></SidebarFooter></Sidebar>
 <div className="app-shell"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger className="mobile-trigger"/><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="topbar-right"><span className="demo-pill">{demo?"Sample data":"Your transactions"}</span><span className="avatar">V</span></div></header>
 <main className="page"><div className="page-title"><div><div className="eyebrow">THE BIG PICTURE</div><h1>{view==="Overview"?"Your spending, at a glance":view}</h1><p>{view==="Recurring"?"The payments that come around again. All available history.":view==="AI insights"?"A conversation with your financial picture.":view==="Accounts"?"Bring your statements together, one card at a time.":"All your cards. A clearer view of where your money goes."}</p></div><button className="primary-button" onClick={openImport}><Upload size={16}/>Import transactions</button></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={load}>Retry</button></div>}
 {loading&&<div className="loading-line" role="status"><Skeleton className="h-3 w-36"/>Loading your transactions…</div>}
 {view!=="Accounts"&&<div className="filter-row"><Select value={month} onValueChange={setMonth} disabled={view==="Recurring"}><SelectTrigger aria-label="Select period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All time</SelectItem>{months.map(m=><SelectItem key={m} value={m}>{new Date(m+"-01T12:00:00Z").toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</SelectItem>)}</SelectContent></Select><Select value={source} onValueChange={setSource}><SelectTrigger aria-label="Filter accounts"><CreditCard size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All accounts</SelectItem><SelectItem value="amex">American Express</SelectItem><SelectItem value="discover">Discover</SelectItem></SelectContent></Select></div>}
 {view==="Overview"&&<><section className="stats-grid"><div className="stat-card"><div className="stat-label">Total spent <span><ArrowUpRight size={17}/></span></div><div className="stat-number">{money(total)}</div><div className="stat-foot">Purchases minus refunds · payments excluded</div></div><div className="stat-card"><div className="stat-label">Transactions <span><ArrowDownLeft size={17}/></span></div><div className="stat-number">{current.length}<span className="stat-unit">in this period</span></div><div className="stat-foot">Across {new Set(current.map(t=>t.source)).size} accounts</div></div><div className="stat-card"><div className="stat-label">Top category <span><Wallet size={17}/></span></div><div className="stat-number smaller">{categories[0]?.name||"—"}</div><div className="stat-foot"><strong>{money(categories[0]?.value||0)}</strong> in this category</div></div></section>
 <div className="overview-grid"><section className="panel spending-panel"><div className="panel-heading"><div><h2>Where it’s going</h2><p>Spending by category</p></div><span className="subtle-label">SELECTED PERIOD</span></div><div className="category-layout"><div className="donut" style={{background:`conic-gradient(${categories.map((c,i)=>`${colors[i%colors.length]} ${categories.slice(0,i).reduce((s,x)=>s+x.value,0)/categories.reduce((s,x)=>s+x.value,0)*100}% ${categories.slice(0,i+1).reduce((s,x)=>s+x.value,0)/categories.reduce((s,x)=>s+x.value,0)*100}%`).join(",")})`}}><div><small>Total spent</small><strong>{money(total)}</strong><span>{categories.length} categories</span></div></div><div className="category-legend">{categories.map((c,i)=><div key={c.name}><i style={{background:colors[i%colors.length]}}/><span>{c.name}</span><strong>{money(c.value)}</strong></div>)}</div></div></section><section className="insight-teaser"><span className="insight-symbol"><Sparkles size={23}/></span><div className="eyebrow">A FRESH PERSPECTIVE</div><h2>Meet your money.<br/>Make sense of it.</h2><p>Ask about your spending, spot patterns, and understand what comes around every month.</p><button onClick={()=>setView("AI insights")}>Ask Ledger <ArrowUpRight size={17}/></button><span className="insight-caption">Insights grounded in your transactions</span></section></div>
 <section className="panel transactions-panel"><div className="panel-heading"><div><h2>Recent transactions <span className="count-label">{current.length}</span></h2><p>A little bit of your everyday, all in one place.</p></div><button className="text-button" onClick={()=>setView("Transactions")}>View all transactions <ArrowRight size={16}/></button></div><TransactionTable rows={current.slice(0,6)}/></section>
 </>}
 {view==="Transactions"&&<TransactionsView rows={current} onImport={openImport}/>}
 {view==="Recurring"&&<RecurringView rows={accountRows} onImport={openImport}/>}
 {view==="Accounts"&&<AccountsView rows={rows} demo={demo} onImport={openImport}/>}
 {view==="AI insights"&&<InsightsView demo={demo} aiConfigured={aiConfigured} month={month} source={source}/>}
 <ImportDialog open={importOpen} onOpenChange={setImportOpen} onImported={imported}/><Toaster position="bottom-right"/>
 <footer className="page-footer"><span>Made for a little more peace of mind.</span><span>{demo?"USD · Sample transactions for exploration":"USD · Based on imported statements"}</span></footer></main></div></SidebarProvider>;
}
